# Generated by Django 3.0.6 on 2020-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('contents', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
