# Generated by Django 3.0.6 on 2020-05-07 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_auto_20200505_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='publishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
